apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ingress-validate.fullname" . }}
  namespace: {{ .Release.Namespace  }}
  labels:
    app: {{ template "ingress-validate.name" . }}
    chart: {{ template "ingress-validate.chart" . }}
    release: {{ .Release.Name }}
data:
  default.conf: |-
    server {
        listen       80;
        server_name  ~^(?<basehost>.+)\.{{ .Values.domain }}$;
        location / {
            return 200 $basehost\n;
        }
    }
